services:
  - type: web
    name: resume-to-portfolio-website
    env: node
    region: oregon
    rootDir: backend
    buildCommand: npm install && cd ../frontend && npm install && npm run build
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: NETLIFY_AUTH_TOKEN
        sync: false